### ISSUE TITLE
it's not able to be built anyway

### ISSUE THREAD

**Issue by abcdef123ghi** [miyako/msvc-freexl#1]
Hi Miyako
    I tried to build this project on VS2019,I didn't try build this project on VS2015,but it doesn't work anyway

it says

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2491	'round': definition of dllimport function not allowed	freexl	D:\opensourcelibrary\CPP\msvc-freexl-master\freexl\freexl.c	96	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2491	'lround': definition of dllimport function not allowed	freexl	D:\opensourcelibrary\CPP\msvc-freexl-master\freexl\freexl.c	105

**Comment by miyako** [comment]
notice the library is a static link. you can not link a library that was built using a different visual c sdk. this is normal. you need to compile the library from source.

**Comment by abcdef123ghi** [comment]
> notice the library is a static link. you can not link a library that was built using a different visual c sdk. this is normal. you need to compile the library from source.

Thanks for replying, I appreciate it
